name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 103.149.105.159
          port: 22
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/meetbrief
            git fetch origin
            git checkout prod
            git pull origin prod
            npm install --production=false
            npx prisma generate
            npx prisma db push
            npm run build
            pm2 restart meetbrief || pm2 start npm --name meetbrief -- start -- -p 3002
