import { NextResponse } from "next/server";
import { db }           from "@/lib/db";

const CONTACTS = [
  { name: "Betopia Cloud", email: "betopiacloud@betopialimited.com" },
  { name: "Md. Saiful Islam", email: "saiful.islam@betopialimited.com" },
  { name: "Shawon Ghosh", email: "shawon.ghosh@betopialimited.com" },
  { name: "Md. Jahidul Islam", email: "jahidul.islam@betopialimited.com" },
  { name: "Ahmed Noor Alam", email: "ahmed.alam@betopialimited.com" },
  { name: "Adib Ebna Jamal", email: "adib.jamal@betopialimited.com" },
  { name: "Anik Mahmud Tushar", email: "anik@betopialimited.com" },
  { name: "Md. Naimul Hasan Durjay", email: "durjay@betopialimited.com" },
  { name: "Md. Shahin Showkat Ovee", email: "ovee@betopialimited.com" },
  { name: "Md Shahidullah", email: "shahidullah@betopialimited.com" },
  { name: "Sirazum Monira", email: "smonira@betopialimited.com" },
  { name: "Sondip Roy", email: "sondip.roy@betopialimited.com" },
  { name: "Md Mosabbir Hossain", email: "mosabbir@betopialimited.com" },
  { name: "Md. Ariful Islam", email: "arif@betopialimited.com" },
  { name: "Fabliha Chowdhury", email: "fabliha@betopialimited.com" },
  { name: "Farjana Yesmin", email: "farjana.yesmin@betopialimited.com" },
  { name: "Md Raton Islam", email: "raton@betopialimited.com" },
  { name: "Mohammad Shahiriar Hasan Badhon", email: "shahriar@betopialimited.com" },
  { name: "Srabanti Dey", email: "srabanti.dey@betopialimited.com" },
  { name: "Rakibul Islam Shiku", email: "rakibul@betopialimited.com" },
  { name: "Jahid Hassan", email: "jahid.hassan@betopialimited.com" },
  { name: "Muhammad Monir Hossain", email: "muhammad@betopialimited.com" },
  { name: "Mushfiqur Rahman", email: "mushfiqur@betopialimited.com" },
  { name: "Sales", email: "sales@betopialimited.com" },
  { name: "Mayinuddin Munna", email: "mayinuddin@betopialimited.com" },
  { name: "Md. Ashraful Mamun", email: "ashraful@betopialimited.com" },
  { name: "Rakibul Hassan", email: "rakibul.hassan@betopialimited.com" },
  { name: "Demo", email: "demo@betopialimited.com" },
  { name: "Rafsun Ahmad", email: "rafsun.ahmad@betopialimited.com" },
  { name: "Muhit Al Faisal", email: "muhit.faisal@betopialimited.com" },
  { name: "Nur Mohammod Sarkar (Tohad)", email: "nur.sarkar@betopialimited.com" },
  { name: "Emdad Hossain", email: "emdad.hossain@betopialimited.com" },
  { name: "Partners", email: "partners@betopialimited.com" },
  { name: "Fatema Tuz Zohora", email: "fatema.zohora@betopialimited.com" },
  { name: "Mohammad Masum Jahangir", email: "masum@betopialimited.com" },
  { name: "Rajib Hossain", email: "rajib.hossain@betopialimited.com" },
  { name: "Cloud Admin", email: "cloud.admin@betopialimited.com" },
  { name: "Partner", email: "partner@betopialimited.com" },
  { name: "Betopia Partners", email: "betopia.partners@betopialimited.com" },
  { name: "Info", email: "info@betopialimited.com" },
  { name: "Feedback", email: "feedback@betopialimited.com" },
  { name: "Cloud Admin AWS", email: "cloudadmin.aws@betopialimited.com" },
  { name: "DMARC", email: "dmarc@betopialimited.com" },
  { name: "Srabanti Dey (OEM)", email: "srabantidey.oem@betopialimited.com" },
  { name: "Support", email: "support@betopialimited.com" },
  { name: "Admin Betopia", email: "admin@betopialimited.com" },
  { name: "Md. Saifullah Al Mamun", email: "saifullah.mamun@betopiagroup.com" },
  { name: "Md. Rakibul Islam", email: "mrakibul@betopiagroup.com" },
  { name: "Abdullah Al Alamin", email: "abdullah@betopiagroup.com" },
  { name: "Md. Rezaul Karim", email: "rezaulkarim@betopiagroup.com" },
  { name: "Md. Sajedul Islam", email: "sajedul.islam@betopiagroup.com" },
  { name: "Mohammed Azizul Haq", email: "azizul.haq@betopiagroup.com" },
  { name: "Md. Nasir", email: "nasir@betopiagroup.com" },
  { name: "Rakibul Islam (Shiku)", email: "rakib@betopiagroup.com" },
  { name: "Md. Ashraful Mamun", email: "ashraful@betopiagroup.com" },
  { name: "Md. Atikul Islam", email: "atikul@betopiagroup.com" },
  { name: "Israt Jahan Onu", email: "onu@betopiagroup.com" },
  { name: "Mehejabin Sarker Chowa", email: "mehejabin@betopiagroup.com" },
  { name: "Nazmus Sakib", email: "nazmus.sakib@betopiagroup.com" },
  { name: "Md. Atiqur Rahman Rinku", email: "rinku@betopiagroup.com" },
  { name: "Md. Hashibur Rahman", email: "hashibur@betopiagroup.com" },
  { name: "Oliur Rahman", email: "oliur@betopiagroup.com" },
  { name: "Tasnuva Sharmin Sinthiya", email: "tasnuva@betopiagroup.com" },
  { name: "Fatema Akter", email: "fatema@betopiagroup.com" },
  { name: "Md. Amanotullah", email: "amanotullah@betopiagroup.com" },
  { name: "Muntasir Raihan", email: "muntasir@betopiagroup.com" },
  { name: "Md. Hasibul Akber Shanto", email: "hasibul.akber@betopiagroup.com" },
  { name: "Anika Tahsin", email: "anika.tahsin@betopiagroup.com" },
  { name: "Niaz Sultana", email: "niaz@betopiagroup.com" },
  { name: "Md. Tariqul Islam", email: "tariqul@betopiagroup.com" },
  { name: "Muhammadullah", email: "muhammadullah@betopiagroup.com" },
  { name: "Sahima Rahman", email: "sahima@betopiagroup.com" },
  { name: "Sharmin Akter Shammi", email: "sharmin@betopiagroup.com" },
  { name: "Eftekhar Hasib", email: "eftekhar@betopiagroup.com" },
  { name: "Md. Fuad Hasan Chomok", email: "chomok@betopiagroup.com" },
  { name: "Imarana Jahan", email: "imarana@betopiagroup.com" },
  { name: "Protik Neogi", email: "protik@betopiagroup.com" },
  { name: "Ashiqur Rahman", email: "ashiqur@betopiagroup.com" },
  { name: "Jahid Hassan Shawon", email: "jahid@betopiagroup.com" },
  { name: "Md. Ahad", email: "mdahad@betopiagroup.com" },
  { name: "Dipa Rany Biswas", email: "diparany@betopiagroup.com" },
  { name: "Rakhi Parvin Banya", email: "rakhi@betopiagroup.com" },
  { name: "Mainur Rahman Sourov", email: "mainur@betopiagroup.com" },
  { name: "Md. Fahmidul Haque Ankur", email: "fahmidul@betopiagroup.com" },
  { name: "Tuly Rahman", email: "tuly@betopiagroup.com" },
  { name: "Md. Wahidujjaman", email: "wahidujjaman@betopiagroup.com" },
  { name: "Tonima Jahan", email: "tonima@betopiagroup.com" },
  { name: "Hafijur Rahman", email: "hafijur131@betopiagroup.com" },
  { name: "Md. Razay Rabbi", email: "razay@betopiagroup.com" },
  { name: "Arpita Das", email: "arpita.das@betopiagroup.com" },
  { name: "Esrat Jahan", email: "esrat@betopiagroup.com" },
  { name: "Umma Hany", email: "umme@betopiagroup.com" },
  { name: "Salma Binte Osman", email: "salma@betopiagroup.com" },
  { name: "Msr. Esrat Jahan Nisa", email: "esrat.nisa@betopiagroup.com" },
  { name: "Rezwan Al Bukhar", email: "rezwan@betopiagroup.com" },
  { name: "Md. Riyad Hossain", email: "riyad.hossain@betopiagroup.com" },
  { name: "Mohammad Nishad Kabir", email: "nishad@betopiagroup.com" },
  { name: "Md Mahabub Morshed", email: "mahabub@betopiagroup.com" },
  { name: "Md. Al Amin", email: "alamin@betopiagroup.com" },
  { name: "MD. Rayhan Hassan Badhon", email: "rayhanhassan@betopiagroup.com" },
  { name: "Md. Mahbub Hasan Khan", email: "mahbubkhan@betopiagroup.com" },
  { name: "Md. Omar Faruk", email: "omarfaruk@betopiagroup.com" },
  { name: "Mahamudul Hasan", email: "mahamudul@betopiagroup.com" },
  { name: "Hafijur Rahman", email: "hafijur@betopiagroup.com" },
  { name: "Mesbahul Islam", email: "mesbahul@betopiagroup.com" },
  { name: "Md. Shahid Ullah", email: "shahid@betopiagroup.com" },
  { name: "D.M. Ajmain Shaharir", email: "ajmain@betopiagroup.com" },
  { name: "Md. Rubel Hossain", email: "rubel.hossain@betopiagroup.com" },
  { name: "Md Azizul Alim", email: "mdazizul@betopiagroup.com" },
  { name: "Kazi Azizul Islam", email: "azizul@betopiagroup.com" },
  { name: "Md. Omar Nasif Antar", email: "nasif@betopiagroup.com" },
  { name: "Shahriar Hossain", email: "shahriar.hossain@betopiagroup.com" },
  { name: "Khaleda Khanam", email: "meem@betopiagroup.com" },
  { name: "Tahmid Jawwad", email: "tahmid@betopiagroup.com" },
  { name: "Md. Rayhan Kabir", email: "rayhan@betopiagroup.com" },
  { name: "Md. Sumon Ali", email: "sumon@betopiagroup.com" },
  { name: "Md. Maruf Hossain Ananta", email: "ananta@betopiagroup.com" },
  { name: "Tauqir Sheikh", email: "tauqir@betopiagroup.com" },
  { name: "Md. Rokun Islam", email: "rokun@betopiagroup.com" },
  { name: "Arsadul Islam", email: "neloy@betopiagroup.com" },
  { name: "Md. Shazzad Hossain Aurango", email: "aurango@betopiagroup.com" },
  { name: "Md. Sohan Ali", email: "sohan@betopiagroup.com" },
  { name: "Md. Alshaharia", email: "alshaharia@betopiagroup.com" },
  { name: "Toukir Ahmed", email: "toukir@betopiagroup.com" },
  { name: "Alif Shariyar", email: "alif@betopiagroup.com" },
  { name: "Sakibul Alam Shoybal", email: "sakibul@betopiagroup.com" },
  { name: "Shifatur Rahman", email: "shifatur@betopiagroup.com" },
  { name: "Md. Rafiul Islam", email: "rafiul@betopiagroup.com" },
  { name: "Md. Atikur Rahman", email: "atikurrahman@betopiagroup.com" },
  { name: "Md. Asifur Rahman", email: "asifur@betopiagroup.com" },
  { name: "Md. Rifat Hossain", email: "rifathossain@betopiagroup.com" },
  { name: "Md. Shibly Hasan Janok", email: "shibly@betopiagroup.com" },
  { name: "Md Shejan Ali", email: "shejan@betopiagroup.com" },
  { name: "Md Jahidul Islam", email: "jahidul@betopiagroup.com" },
  { name: "Sharif Hossain", email: "sharifhossain@betopiagroup.com" },
  { name: "Saimon Billah", email: "saimon@betopiagroup.com" },
  { name: "Antor Saha", email: "antorsaha@betopiagroup.com" },
  { name: "Ashraful Islam Akash", email: "ashraful.akash@betopiagroup.com" },
  { name: "Tanvir Anjum Nayem", email: "tanviranjum@betopiagroup.com" },
  { name: "Azmul Hoque", email: "azmul@betopiagroup.com" },
  { name: "Sajib Chandra Mazumder", email: "sajibchandra@betopiagroup.com" },
  { name: "Shimon Bhowmick", email: "shimon@betopiagroup.com" },
  { name: "Habibul Bashar", email: "habibul.bashar@betopiagroup.com" },
  { name: "Md. Asif Mahmud Anik", email: "asif.mahmud@betopiagroup.com" },
  { name: "Jisan Khan", email: "jisan@betopiagroup.com" },
  { name: "Ahmad Ullah", email: "ahmad.ullah@betopiagroup.com" },
  { name: "Md. Biplob Hossan", email: "biplob.hossan@betopiagroup.com" },
  { name: "Md. Raiyat Bin Majib Rehan", email: "raiyat@betopiagroup.com" },
  { name: "Md. Sabbir Rahman", email: "sabbir@betopiagroup.com" },
  { name: "Md. Rifat Al Shajid", email: "rifat@betopiagroup.com" },
  { name: "Md. Rizvi Ahmed Rumon", email: "rizviahmedrumon@gmail.com" },
  { name: "Md. Rayhan Ali", email: "bdmdrayhan.com@gmail.com" },
  { name: "Rony Chowdhury", email: "rony.nstp17@gmail.com" },
  { name: "Shafiqul Islam", email: "shafiq@betopiagroup.com" },
  { name: "Md. Rumman Khan", email: "rumman@datainsightio.com" },
  { name: "Md. Mottakin Rahat", email: "mottakin@betopiagroup.com" },
  { name: "Arif Mahamud", email: "arif.mahamud@betopiagroup.com" },
  { name: "Atikul Islam Ashik", email: "atikul.islam@betopiagroup.com" },
  { name: "Mohammad Sanjid Rayhan", email: "sanjid.bdc@gmail.com" },
  { name: "Md. Naimul Hasan Durjay", email: "durjay@betopiagroup.com" },
  { name: "Gazi Alauddin", email: "gazialauddin@betopiagroup.com" },
  { name: "Farvez Hossen", email: "farvez@betopiagroup.com" },
  { name: "Anisur Rahman Roni", email: "roni@scaleupadsagency.com" },
  { name: "Md. Forman Ali", email: "formanali@betopiagroup.com" },
  { name: "Md. Kamruzzaman", email: "kamruzzaman@betopiagroup.com" },
  { name: "Md Raton Islam", email: "ratonislam@gmail.com" },
  { name: "Md. Sheraz Howlader", email: "sheraz@betopiacloud.com" },
  { name: "Ismail Hossain", email: "ismail@betopiagroup.com" },
  { name: "Md. Ariful Islam", email: "arif.islam@betopialimited.com" },
];

export async function POST() {
  // Seed allowed domains
  const domains = ["betopiagroup.com", "betopialimited.com", "betopiacloud.com"];
  for (const domain of domains) {
    await db.allowedDomain.upsert({
      where:  { domain },
      update: { active: true },
      create: { domain, active: true },
    });
  }

  // Seed employee contacts
  let seeded = 0;
  for (const c of CONTACTS) {
    const email = c.email.toLowerCase();
    await db.employeeDirectory.upsert({
      where:  { email },
      update: { name: c.name },
      create: { name: c.name, email },
    });
    seeded++;
  }

  return NextResponse.json({ success: true, seeded, domains: domains.length });
}
